# Site settings
title: Corinne Michaux Fine Arts
email: hausner.lukas@gmx.at
description: > # this means to ignore newlines until "baseurl:"
  Corinne Michaux Fine Arts

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://corinnemichaux.github.io/"

# Build settings
markdown: kramdown
timezone: Europe/Vienna
encoding: utf-8

defaults:
 -
   scope:
     path: ""
   values:
     layout: "default"

sass:
  sass_dir: css

plugins:
  - jekyll-redirect-from
